export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";

export const ASYNC_POST_START = "ASYNC_POST_START";
export const ASYNC_POST_FINISH = "ASYNC_POST_FINISH";
export const ASYNC_POST_ERROR = "ASYNC_POST_ERROR";
